name: deploy to vercel
on:
  push:
    branches: [master, develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Build
        run: |
          yarn
          yarn build
          
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: vercel
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
